import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbarDock';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tech Janta Party',
  description: 'Generated by Team TJP',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="https://res.cloudinary.com/djyk287ep/image/upload/v1731309202/TJP_dgmjtt.png"
          type="image/x-icon"
        />
        <link
          rel="apple-touch-icon"
          href="https://res.cloudinary.com/djyk287ep/image/upload/v1731309202/TJP_dgmjtt.png"
        />
      </head>
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
